title: "Amokh Varma"
author: "Amokh Varma"
description: "Indian Institute of Technology, Delhi"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true          # show site description and social links in the footer
show_excerpts: true        # show article excerpts on the home page
show_frame: false        # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:
  - {title: "CV", url: "/2018MT60527_3rdYear.pdf", icon: newspaper}
  #- {title: "Lab", url: "https://childlanglab.com"}
  - {title: "Projects", file: "Projects.md",icon: project-diagram}

external:                  # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:amokhvarma@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/amokhvarma"}
  - {title: Instagram, icon: instagram , url: "https://www.instagram.com/amokhvarma/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
